### ISSUE TITLE
Add continuous integration tests

### ISSUE THREAD

**Issue by Samasaur1** [aaplmath/CaffeineKit#2]
CaffeineKit should be using continuous integration to run tests. I recommend using [Travis CI](https://travis-ci.com), which is free for open-source projects. Here's a `.travis.yml` file from one of my Swift projects as a reference:

https://github.com/Samasaur1/UtilityKit/blob/1c820cea9d42b16738fd7cbb009116ac82117a5f/.travis.yml#L1-L19

(I can't seem to get inline code working)

**Comment by Samasaur1** [comment]
https://github.com/Samasaur1/UtilityKit/blob/1c820cea9d42b16738fd7cbb009116ac82117a5f/.travis.yml#L1-L19

**Comment by Samasaur1** [comment]
```yaml
os:
- osx
- linux
language: generic
sudo: false
dist: trusty
osx_image: xcode9
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift build
```

**Comment by Samasaur1** [comment]
I'd suggest changing it to:

```yaml
os:
- osx
- linux
language: generic
sudo: false
dist: trusty
osx_image: xcode9
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift clean test
```
